use student_growth_tracker;

drop table if exists student_grade;
drop table if exists student_classes;
drop table if exists class_grade;
drop table if exists grade_standard;
drop table if exists standard;
drop table if exists student;
drop table if exists gradebook;
drop table if exists classes;
drop table if exists grade;
drop table if exists grade_type;
drop table if exists contentarea;
drop table if exists school_member;
drop table if exists school;
drop table if exists auth_permission;
drop table if exists auth_event;
drop table if exists auth_cas;
drop table if exists auth_membership;
drop table if exists auth_group;
drop table if exists auth_user;
